name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      srs_tag:
        description: 'SRS Version tag'
        required: true
        default: '2.2.0.2'
      image_tag:
        description: 'Docker image tag'
        required: true
        default: '2.2.0.2-beta'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download SRS Release Zip
        run: |
          curl -L -o DCS-SimpleRadioStandalone.zip https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/download/${{ github.event.inputs.srs_tag }}/DCS-SimpleRadioStandalone-${{ github.event.inputs.srs_tag }}.zip

      - name: Extract SRS-Server-Commandline
        run: |
          unzip -j DCS-SimpleRadioStandalone.zip 'ServerCommandLine-Linux/SRS-Server-Commandline' -d .

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dcs-srs-server:${{ github.event.inputs.image_tag }}

      - name: Save Docker image as tarball
        run: docker save dcs-srs-server:${{ github.event.inputs.image_tag }} -o dcs-srs-server.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: dcs-srs-server-image
          path: dcs-srs-server.tar